# Generated by Django 4.1.5 on 2023-01-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_details',
            old_name='created_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='patient_details',
            old_name='updated_at',
            new_name='start_time',
        ),
    ]
